#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')

parser = argparse.ArgumentParser(description='Build containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--from-cache', '-f', '-c', action='store_true',
                    default=None, help='build the images from the cache')

parser.add_argument('--run', '-r', '--up', '-u', action='store_true',
                    default=None, help='bring the containers online')

args = parser.parse_args()

cmd = ['docker-compose', '-f', compose_path, '--verbose', 'build']
if not args.from_cache:
    cmd.append('--no-cache')

proc = subprocess.Popen(cmd)
proc.communicate()

if args.run:
    cmd = [os.path.join(dirname, 'runContainers')]
    if args.fromcache:
        cmd.append('--fromcache')

    proc = subprocess.Popen(cmd)
    proc.communicate()

print('Built container images.')